### ISSUE TITLE
Missing annunciators

### ISSUE THREAD

**Issue by TheFrett** [TheFrett/msfs_g36_project#1]
AC DOOR EXTD
STARTER ENGD
AFT DOOR

![image](https://user-images.githubusercontent.com/11409383/92335939-03f25900-f09c-11ea-8d5b-db29f9601549.png)

**Comment by TheFrett** [comment]
See POH 7-63 and 7-64 for more missing annunciators

**Comment by TheFrett** [comment]
I am currently implementing most of these...

**Comment by TheFrett** [comment]
Does anyone know the simvars for alternator load? I can only find battery loads. Or do they change to alternator loads when the alternators are active?

**Comment by 50North4West** [comment]
There is a 'ELECTRICAL GENALT BUS VOLTAGE' and a 'ELECTRICAL GENALT BUS AMPS' which might work? There is also a 'ELECTRICAL TOTAL LOAD AMPS' which could be used to subtract from 'ELECTRICAL BATTERY LOAD' to give the remaining load perhaps???? Got these from the Simvars.exe (D:\MSFS SDK\Samples\SimvarWatcher\bin\x64\Release)

**Comment by 50North4West** [comment]
When turning on the batteries the Alt 1-2 INOP warning shows/beeps. Need to check the POH but from a usabilty standpoint do we want to add a check that the engine is running first??

**Comment by TheFrett** [comment]
> There is a 'ELECTRICAL GENALT BUS VOLTAGE' and a 'ELECTRICAL GENALT BUS AMPS' which might work? There is also a 'ELECTRICAL TOTAL LOAD AMPS' which could be used to subtract from 'ELECTRICAL BATTERY LOAD' to give the remaining load perhaps???? Got these from the Simvars.exe (D:\MSFS SDK\Samples\SimvarWatcher\bin\x64\Release)

That simvarwatcher is extremely useful, I didn't know about it, thanks!

**Comment by TheFrett** [comment]
> When turning on the batteries the Alt 1-2 INOP warning shows/beeps. Need to check the POH but from a usabilty standpoint do we want to add a check that the engine is running first?? The alarm goes off when turning switches on even without engine running but the alternators wouldn't be giving any voltage???

We'll have to check the POH / Ask JuiceBox on the forum as an ex G36 pilot

**Comment by 50North4West** [comment]
> 
> 
> > There is a 'ELECTRICAL GENALT BUS VOLTAGE' and a 'ELECTRICAL GENALT BUS AMPS' which might work? There is also a 'ELECTRICAL TOTAL LOAD AMPS' which could be used to subtract from 'ELECTRICAL BATTERY LOAD' to give the remaining load perhaps???? Got these from the Simvars.exe (D:\MSFS SDK\Samples\SimvarWatcher\bin\x64\Release)
> 
> That simvarwatcher is extremely useful, I didn't know about it, thanks!

I know! I found half a reference to it on the fsdeveloper forum and it changed the massive trial and error time it takes to do stuff! Talking about sharing knowledge; do you know a quicker way of reloading mod changes other than having to close a flight, go to main menu, setup another flight, check etc. This is the bit that is slowing me down as the checklists are real trial and error at the moment.

**Comment by TheFrett** [comment]
I implemented an engine running check, based on JuiceBox's feedback. Thanks for asking!

I don't know. In fact, as for flight dynamics I tested once if changes affect the aircraft if reloading from the main menu. They didn't (will have to check again, since you suggest that for the checklist that does work). So I restart MSFS every time I make a change.

I wish changes are effective after reloading from the SDK aircraft selector. Maybe they are for non-cfg files?

**Comment by 50North4West** [comment]
I've been able to just go back to the main menu, start a new flight for changes to the annunciators and checklists which I suppose is something. I think FS reads the lalyout.json on initial load so any changes there need a complete restart.

**Comment by TheFrett** [comment]
Can confirm that for editing XML files only a restart of the flight from the main menu is needed. For cfg files a complete restart is required. Both were already present in the layout json...

**Comment by TheFrett** [comment]
https://www.fsdeveloper.com/forum/threads/change-default-aircraft-flight-dynamic.448482/post-851725

Check this post. Can't try it now, but if this works that is going to significantly speed up tweaking and debugging!

**Comment by 50North4West** [comment]
That would be awesome if we can! Will try and have a go this evening and will report back.

**Comment by 50North4West** [comment]
> 
> 
> https://www.fsdeveloper.com/forum/threads/change-default-aircraft-flight-dynamic.448482/post-851725
> 
> Check this post. Can't try it now, but if this works that is going to significantly speed up tweaking and debugging!

Not sure this is working on my install; I keep CTD when trying to load the checklist again. :-( Could be related to the fact I am using a laptop! I get 20fps ish so any sort of load and it throws a wobbly!

**Comment by TheFrett** [comment]
It works for me at least! Editing numbers in the CFG files and seeing the effect within a few seconds makes it so much easier!
