### ISSUE TITLE
flight physics

### ISSUE THREAD

**Issue by Blue2hark** [TheFrett/msfs_g36_project#101]
Hello I find the physics of the flight Absent on the gusts of wind in the near it does not float before touching it it falls like a stone not enough to work damage for an airplane downloaded at more than 10k the performance of the plane I find it not great it has trouble climbing to its altitude flight 18,500 feet cruising speed 176 kts and at 8 thousand feet I am not at 176 kts rather 140 kts

**Comment by 50North4West** [comment]
Hi 

This is the normally aspirated aircraft, although listed as a service ceiling of 18,500ft the actual aircraft will struggle to get there. According to the POH (which only shows performance figures up to 16k) at full throttle / 2500 rpm you should be achieving 150 kts tas. 

The normally aspirated Bonanza is much happier at 8000-10000ft and we are confident that the performance figures are correct. At 8000ft you should be making 167kts TAS, with a cruise weight of 3400lbs at ISA.
