### ISSUE TITLE
IAS Gauge

### ISSUE THREAD

**Issue by Aesculab** [TheFrett/msfs_g36_project#105]
**Describe the bug**
IAS showing on Gauge != IAS in G1000nxi

**To Reproduce**
1. Start on a Runway or Cold & Dark (Place doesn't matter)
2. Taxi & Takeoff
3. Compare IAS on G1000nxi vs. IAS Gauge on Co-Pilots side.
4. Notice difference

**Expected behavior**
IAS shown on both instruments should be almost the same.

**Screenshots**
IAS Deviation
![IAS](https://user-images.githubusercontent.com/35341633/143876525-56d0965b-9bb7-4320-beb1-1053c186e70f.png)

**Background Info (please complete the following information):**
 - Sim Build: 1.21.13.0
 - Mods: WT NXi v0.9.2 via M$-Store & the following in Community-Folder:
 - ![Mods](https://user-images.githubusercontent.com/35341633/143877673-e68bc4bd-aac6-47b4-8174-46479c3ce901.png)

**Comment by 50North4West** [comment]
Thanks so much for your bug report! This issue was introduced during one of the sim updates and we have a fix in our most recent beta (soon to be released) in the #106 development channel.
