### ISSUE TITLE
Praise, Bug Report, Request

### ISSUE THREAD

**Issue by triflyman** [TheFrett/msfs_g36_project#109]
First...thank you so much for this.  Haven't flown the Bonanza in over a year because of what the Asobo version was.  Now with your mod it's so much more satisfying to fly.

Second...not sure if this is yours or the G1000 NXI...when I click on "Engine" and then "System" the "GAL REM", "GAL USED", "ENDUR" and "Range NM" numbers are all over the place and seem to have nothing to do with what is going on in the aircraft.

Third...I noticed the aircraft livery in your "Hanger" appears to be of the 60th Anniversary edition.  I downloaded this livery from flightsim.to and followed your directions to get it to work with your mod...but no luck.  Tried several things, even deleted the Panel folder as that was causing a CTD in the sim...but still won't show up.  Can you share with me what you did to get it to work with your mod please?

Thank you so much.

Garry

**Comment by arl4223** [comment]
> Second...not sure if this is yours or the G1000 NXI...when I click on "Engine" and then "System" the "GAL REM", "GAL USED", "ENDUR" and "Range NM" numbers are all over the place and seem to have nothing to do with what is going on in the aircraft.

Did you reset the fuel stats in the G1000 NXi? There are some soft buttons right at the `Engine` page.

**Comment by triflyman** [comment]
Not sure what I did but I think I must have screwed it up somehow.  Have done 3 flights since and it worked correctly.

Thanks,
Garry
