### ISSUE TITLE
Asobo files

### ISSUE THREAD

**Issue by TheFrett** [TheFrett/msfs_g36_project#15]
Could someone make a pull request for the new asobo-0.1.47 branch with the default engines.cfg and flight_model.cfg. I lost these files (repair doesn't allow redownload for some reason). I didn't have a plan when I started this and edited default files in the official folder ...

**Comment by Dabako** [comment]
Hope that was what you wanted. If you need more files just write which you need.
And thanks for your work!

**Comment by TheFrett** [comment]
Yes, perfect! Thanks!
