### ISSUE TITLE
Landing Lights & Nav Lights don't work. 

### ISSUE THREAD

**Issue by Matchrocket** [TheFrett/msfs_g36_project#29]
Per subject, reviewing interior xml file for correct template usage.   These lights work on the 172 OKAY.

**Comment by Matchrocket** [comment]
No-Mode they work perfectly fine.    Default interior.xml file loaded w/the mode breaks it still.   Not sure why.

**Comment by TheFrett** [comment]
Could you pull the latest dev-version and use it? Someone fixed them.

**Comment by TheFrett** [comment]
Nav lights are working for me...?

**Comment by Exp232** [comment]
This has been resolved.
