### ISSUE TITLE
No Input

### ISSUE THREAD

**Issue by strongbow1** [TheFrett/msfs_g36_project#41]
After installing this AMAZING mod. I restarted my sim after the first few hours of flying this. Once loaded in. Nothing was working. No joystick movement nothing. I had to reload into a different plane then back to the Bonanza for everything to work.

That is the only issue I have with this mod. Thank you for creating something this Amazing.

**Comment by TheFrett** [comment]
I have no idea what this could be. First time I hear about it. 

Is your installation correct?

**Comment by strongbow1** [comment]
Yes it is correct. Don't think dragging and dropping into the community folder is rocket science. Well at least I hope not.

**Comment by TheFrett** [comment]
Mandatory G1000 mod also there (not that it should interfere with controls, but to be sure)?
