### ISSUE TITLE
SYSTEM page in PFD reversionary mode

### ISSUE THREAD

**Issue by Viniter** [TheFrett/msfs_g36_project#42]
Currently there is no way to open up the SYSTEM page/column in the PFD reversionary mode (with only the PFD running). This makes it impossible to accurately follow the pre-flight checklist - particularly the battery check, without turning on the Avionics Master switch. POH (and the ingame checklist for that matter) clearly asks for the PFD be in reversionary mode for the battery check, which makes sense since you want to minimize the battery drain. I'm thinking it might be only a matter of mapping a soft key, since the SYSTEM page is already working great on the MFD.

It's a minor nitpick on overall awesome mod, but I thought I'd report it. Great work! :)

**Comment by TheFrett** [comment]
This is a WT G1000 issue, which I actually posted some time ago already.

https://github.com/Working-Title-MSFS-Mods/fspackages/issues/127
