### ISSUE TITLE
[BUG] Mixture setting is not correct

### ISSUE THREAD

**Issue by St54Kevin** [TheFrett/msfs_g36_project#53]
Mod version 0.5.0.

Noticed this also with the default aircraft. 
Procedures say to set mixture full rich before takeoff and landing, but the airplane doesn't produce max power at that setting. When doing a run up with full Throttle setting you have to pull back mixture to around 86% to have the highest fuel flow. In cruise or climb this setting also corresponds to the max power setting. I flew around 100 hrs on the F33A with the IO-520 and we didn't have that struggle with the mixture.

I love that the plane is getting love by the community. The lack of performance with the default was something bothering me the most. Keep it up!

**Comment by TheFrett** [comment]
This is a known issue. Unfortunately we have no access to the fuel/air ratio tables nor can we alter the response of the engine to certain mixture settings... We will have to beg Asobo for a fix...

**Comment by St54Kevin** [comment]
> This is a known issue. Unfortunately we have no access to the fuel/air ratio tables nor can we alter the response of the engine to certain mixture settings... We will have to beg Asobo for a fix...

That's a bummer, thanks for the response
