### ISSUE TITLE
Engine stopping at 0% throttle

### ISSUE THREAD

**Issue by MatchstickUK** [TheFrett/msfs_g36_project#60]
I'm noticing the engine sometimes stopping when the engine is set to 0% throttle - it's particulatly noticable when starting a flight on the runway, when the engine stops immediately when the sim starts.

But it will also happen other times when throttle is set to zero,.

**Comment by TheFrett** [comment]
Please see the FAQ in on the MSFS Forums (first post in main thread). 

This happens to a cold engine.

**Comment by MatchstickUK** [comment]
So is there a way to change the engine state when starting on the runway to reflect the fact that the engine should not be cold and stopping at zero throttle ?

**Comment by TheFrett** [comment]
Someone suggested we could increase the throttle position at start, but this will probably still result in the engine quitting when idled too fast. I'm afraid it is a minor inconvenience but one that is worth it for the sake of realism, since the aim of the mod is realism.
