### ISSUE TITLE
CTD when loading Nice landing challenge

### ISSUE THREAD

**Issue by derekschinke** [TheFrett/msfs_g36_project#61]
With Turbo mod and this patch for the turbo mod installed, the game CTDs when a landing challenge with the plane is loaded. Loads into the world map just fine, and without the mod installed it loads the landing challenge fine.

**Comment by TheFrett** [comment]
Does this also happen to the standalone package? I.e. the non-turbo version?

**Comment by derekschinke** [comment]
Ugh, it does, and also when none of your mods are installed. Gonna have to do more extensive troubleshooting. Thank you and sorry for the incorrect bug report!
