### ISSUE TITLE
No controls, they move but to no effect

### ISSUE THREAD

**Issue by carneirotr** [TheFrett/msfs_g36_project#67]
Latest update on MSFS. Went on to try this plane but no joy. Surfaces move but it does not fly. Can´t take off, put it in the air with slew mode and the same it falls, hard. Throttle works alright. Really weird. All other planes work normally, even improved ones like cj4 and fbw bus. Might be something i´m not doing right? Drag and drop in the community folder with the g1000 improved right? Help this newb (me)

**Comment by tigert** [comment]
Something wrong in your installation.

It is always good to move all mods away from Community-folder prior to updating the sim, and then run it once, quit and install mods back (one by one if you suspect some issues)

**Comment by carneirotr** [comment]
Yes, that did the trick! Awesome, thanks for taking the time to help me!
