### ISSUE TITLE
Lights need to be adjusted (more realistic illumination)

### ISSUE THREAD

**Issue by clompsy** [TheFrett/msfs_g36_project#7]
Just like the TBM project (https://github.com/Uwajimaya/FS2020) we need to adjust the lighting especially for taxi and landing to have a better illumination.
Currently, landing light is not visible from the cockpit and is basically useless.

Here's a video of the illumination of landing lights, they are clearly visible from the cockpit:
https://youtu.be/_-bJHr4Bdd8?t=95

**Comment by TheFrett** [comment]
Looking good!
