### ISSUE TITLE
Update panel.xml in order to comply with the new g1000 mod update

### ISSUE THREAD

**Issue by nikilase** [TheFrett/msfs_g36_project#70]
After the World Update 4 something broke the secondary displays of the G1000 mod. Working Title fixed this bug with the release 3.5 but changed the way that the secondary displays are implemented. The content of the WTEngineDisplay.xml now needs to be inside of the panel.xml. 

I modified the existing panel.xml to contain the content of the WTEngineDisplay.xml and it seemed to work like before the World Update 4. Would be cool if you would go over it and implement the changes in the mod.

[panel.zip](https://github.com/TheFrett/msfs_g36_project/files/6314345/panel.zip)

**Comment by 50North4West** [comment]
@nikilase Woke up this morning to read the WT update, I've amended our code and sent a pull request to @TheFrett with the changes.
