### ISSUE TITLE
Parking brake stuck

### ISSUE THREAD

**Issue by sonnenfeld** [TheFrett/msfs_g36_project#75]
Hello,

there seems to be an issue with the parking brake of the G36 which locks the aircraft in place even though the brakes are released.

How to reproduce:

1. Spawn at EGOV, GA Parking No. 31
2. Set parking brake
3. Start engine using cold start procedure
4. Release parking brake
5. Set throttle to maximum
6. Aircraft remains stuck even at full throttle

Removing the mod fixes that behaviour and the aircraft moves as expected.

**Comment by eoosting** [comment]
is there a visual indication on the control panel that the parking brake is set?

**Comment by sonnenfeld** [comment]
I uploaded a little video. The plane barely moves regardless of the position of the parking brake lever. There is no annunciation on the PFD. Am I missing something?

https://user-images.githubusercontent.com/83171513/116432972-5a89ee80-a849-11eb-87a3-68dbaa7897d9.mp4

**Comment by TheFrett** [comment]
We have seen a number of report of this problem and I even encountered it myself twice, but thus far we haven't found a way to reliably reproduce this. Are you sure it happens every time when following your steps? I have no time to try it now, but if we can finally reproduce it, we can hopefully find the problem...

**Comment by sonnenfeld** [comment]
I tried it again just now and the plane moved, unfortunately. There must be more factors at play here than the ones I initially mentioned. I will do more testing as soon as I have time and record every step.

Interestingly, when I switched the weather from "clear" to "live" the plane seemed bogged down initially but then moved just fine. My original report was also done using live eather if remember correctly.

**Comment by sonnenfeld** [comment]
I have been messing around with the atmosphere and wind settings and was able to reproduce the issue six out of six times I tried. I needed to change the procedure I described initially a bit:

1. On the map screen, set the weather preset to "clear skies" and the time to 12pm
2. Spawn at EGOV, GA Parking No. 31
3. Set pressure (in the weather menu) to 1030.8 hPa
4. Set wind direction to 45°
5. Set windspeed to 30t
6. Set wind gust to 0
7. When starting the engine, the throttle should be in full forward position

This seems to reliably reproduce the issue, at least on my machine. I also have a video but github won't let me upload files > 10MB.

**Comment by atledreier** [comment]
I'll work some more on this too, but I've been able to reliably reproduce this at ENZV, where taxiway G7 enters RWY36. That's usually where i stop to call tower for TO clearance, and I've been consistently stuck there, I get moving by giving it full beans and holding full rudder for a while, then easing off after the aicraft have slithered a little bit. Ususaly gets me rolling again like nothing happened.

My ENZV is a mod though, I just assumed it was that, but I'll look into it more.

**Comment by senegalo** [comment]
i have the same issue and was able to unstuck myself once "by mistake" with the full rudder trick !! 
is there anything i can collect in terms of info that can help fix this issue ?

**Comment by thiagobaltazar2011** [comment]
I have the same problem over and over again. But I couldn't figure out a way to solve it

**Comment by craze** [comment]
I have been able to get unstuck a couple of times by pulling back on the stick a little bit. As if to lift the front wheel out of the ground.

**Comment by N754DW** [comment]
I had this problem, tracked it down to a "G36 75th Anniversary" livery I had downloaded. Removed the livery from the Community folder, brake problem solved.

**Comment by tigert** [comment]
Slew and move just a bit (if you can) also seems to help. I think this is some interaction between the plane and the scenery - maybe the ground type on some parking spots or areas cause trouble?

**Comment by Rothgar57** [comment]
had the same issue once.

**Comment by Pickafivestring** [comment]
The easiest work around is to use the menu bar in game, hit the active pause button, bring the throttle up to nearly full power, then un-pause.  This works every time.

**Comment by 50North4West** [comment]
We have a possible fix in the development branch [https://github.com/TheFrett/msfs_g36_project/tree/Development](https://github.com/TheFrett/msfs_g36_project/tree/Development) this is still in progress however.

**Comment by 50North4West** [comment]
For my sanity later this is the location of the SDK docs https://docs.flightsimulator.com/html/index.htm#t=Samples_And_Tutorials%2FTutorials%2FDefining_A_Flight_Model.htm&rhsearch=contact%20points&rhhlterm=contacts%20contact%20points%20point
