### ISSUE TITLE
Broken as of SU5

### ISSUE THREAD

**Issue by Ungeneer** [TheFrett/msfs_g36_project#76]
As of SU5 it's quite broken. When clicking things like switches or hiding the yoke, the animation doesn't play and when looking from the outside view, the pilot models are A posing.

**Comment by St54Kevin** [comment]
I would also love an update on this mod. Especially with the new SU5 and the WT G100NXi

**Comment by MagicOizo** [comment]
After the SU5 I don't even see a cockpit anymore. Installed WT G1000NXi from the Marketplace as well. Hope this project is still alive and will fix.
