### ISSUE TITLE
Mod makes MSFS crash

### ISSUE THREAD

**Issue by Kiwi0ne** [TheFrett/msfs_g36_project#79]
Hi there. When the mod is installed, along with the G1000 NXi, MSFS crashes. 
I have to uninstall the mod otherwise I can't use the G1000 NXi on the G36.

**Comment by Pickafivestring** [comment]
I've used the NXi as recently as last night, v0.5.1 without any crashes.  I will note that I use MSFS AddonLinker to only load the things I'm going to use for any given flight, so I have no mod conflicts at anytime.

**Comment by Rothgar57** [comment]
I am getting crashing just running this mod.   Seems stable for about 5 min then crashes every time.   Only other mods i am running is spad.nxt and AFC bridge for my Bravo throttle.

**Comment by 50North4West** [comment]
@Rothgar57, @Pickafivestring Do you still experience crashes?

Could you remove all mods except the G36 & WT 0.7.0 and try with this combination? I'd like to try and ensure that the mod is not the root cause before trying to trouble shoot AFC bridge etc.

**Comment by Rothgar57** [comment]
Will Do. I will let you know.
