### ISSUE TITLE
PFD MFD wont turn on

### ISSUE THREAD

**Issue by Rothgar57** [TheFrett/msfs_g36_project#80]
I am using the G1000 mod and cant get the PFD and MFD to turn on. The G1000 mod is loaded before this mod.  I am not really using any other mods. Only mods that i am using spad bridge for my class echo and AFC bridge for bravo throttle control.  These two mods are loaded before the g1000 mod.

**Comment by Rothgar57** [comment]
This problem only seems to occur with the G1000 0.4.1 version 0.4 version works.

**Comment by billw2012** [comment]
I had this same problem, switched to 0.4, however now the range knobs are entirely broken on both displays. They have no interaction area and appear to be stuck in the bottom left position. Do you see the same thing?

**Comment by Rothgar57** [comment]
its working for me.  try removing all other mods.
