### ISSUE TITLE
no information about the engine

### ISSUE THREAD

**Issue by soruse** [TheFrett/msfs_g36_project#88]
0.6.5
I have lost the information about the engine's operation with MFD. The space in which this information was located is now completely black. I don't use any other mods for g36

**Comment by 50North4West** [comment]
Hi - Have you got the Working Title NXi installed from the marketplace? We have recently swapped dependencies from the old WT G1000 to the NXi.

**Comment by soruse** [comment]
I tried g1000 0.4.1  and with the newest NXI from the market and it is the same in every case. There was no such problem in the previous version of the TF G36.

**Comment by 50North4West** [comment]
Just to be sure you only have one or the other WT 1000 installed? And you are using 0.6.5 release?

**Comment by soruse** [comment]
I'm 100% sure it's 0.6.5 - I downloaded it a while earlier. I tested each of the cases individually: pure msfs, with g1000 and separately with the NXI - TF G36 in each case does not show me the engine parameters.

**Comment by 50North4West** [comment]
Ok, Strange.

Do you see a green buses tied message on the PFD display when turning the engine on?

**Comment by soruse** [comment]
I can see the BUSES TIED message but it's white not green - if that means anything

**Comment by 50North4West** [comment]
Sounds like you have some files missing or corrupted somewhere - the buses tied should be green. 

Can you delete our mod and reboot the sim with the default G36 - check engine page on the default G36 with NXi is fine - then redownload 0.6.5 and copy 'z-bonanza-g36-improvement-project' to your community folder - check busses tied is green and hopefully engine pages there as well???

**Comment by 50North4West** [comment]
Don't forget that WT NXi from marketplace is required and the old WT G1000 is now no longer supported, you won't get engine pages with the old WT G1000 installed.

**Comment by th3r00t** [comment]
I am also having this issue, I can confirm the nxi mod working in other aircraft, just not this one.

-- Found the culprit, for me it was the gtn750 mod, hope this helps clear up this issue

**Comment by 50North4West** [comment]
@th3r00t Thanks for that! I will add it to our troubleshooting steps.

**Comment by 50North4West** [comment]
@soruse 

This may seem like a really silly question but you are using the MFD to get to the engine instruments?

Working Title have not implemented the Reversionary Mode on the NXi yet so to get ot the engine page you need to turn on the MFD. This is temporary until the WT team add the reversionary mode.
