### ISSUE TITLE
Engine Pages to MFD

### ISSUE THREAD

**Issue by 50North4West** [TheFrett/msfs_g36_project#9]
There was a request on the forum to see if we can add the engine pages to the MFD/PFD.

They uploaded the G1000 manual / reference guide. Might be worth seeing what we can add?

[G1000 BeechcraftBonanza_CockpitReferenceGuide_A36_G36SystemSoftwareVersion0458.05_(1).pdf](https://github.com/TheFrett/msfs_g36_project/files/5190996/G1000.BeechcraftBonanza_CockpitReferenceGuide_A36_G36SystemSoftwareVersion0458.05_.1.pdf)

**Comment by 50North4West** [comment]
Suggestion in Forum to keep the modification to the G1000 seperate so as to not cause conflicts with other mods; I think this is a good idea. Perhaps a way we can collaborate with @kaosfere4829 on his G1000 mod once we are happy with G36???

**Comment by TheFrett** [comment]
Received a PM as well from @kaosfere4829. To collaborate is a good idea. However, if we change files to make the G36 compatible with the G1000 mod, it also needs to work without the G1000 mod. At least for now. I think that Asobo will adress some G1000 issues and add more features, so it may also be worthwhile to wait for official changes while we provide a compatibility patch of some sort...

**Comment by TheFrett** [comment]
Covered by G1000 mod, closing.
