### ISSUE TITLE
Backup Speed Indicator incorrect reading

### ISSUE THREAD

**Issue by Jason-118** [TheFrett/msfs_g36_project#97]
**Describe the bug**
On version 0.6.6 Beta the backup airspeed indicator incorrectly reads compared to G1000.

**To Reproduce**
Reproduce every time, mostly noticeable during cruise

**Expected behavior**
Both G1000 & Indicated airspeed gauge should match?

**Screenshots**

**Background Info (please complete the following information):**
 - Sim Build: Latest SU6
 - Other mods G1000 NXi

![g36 speed](https://user-images.githubusercontent.com/93329372/140299736-6d625a1a-6da9-4409-8303-b2687ea992fe.png)

(Pitot Heat was on)

**Comment by 50North4West** [comment]
hi @Jason-118 

Thanks for the detailed bug report. We are aware of the issue and this has been logged and acknowledged by Asobo, sadly we are waiting on a fix from there.

**Comment by 50North4West** [comment]
Fixed in https://github.com/TheFrett/msfs_g36_project/tree/development Beta 3 release :-)

**Comment by Jason-118** [comment]
Lets see what MSFS GOTY update does to it....

**Comment by 50North4West** [comment]
Sim update 7 didn't fix the issue but I have added a fix into the newest development build.
